#ifndef JAT_STATUS_H
#define JAT_STATUS_H

enum jat_status {
    JAT_STATUS_SUCCESS = 0,
    JAT_STATUS_INVALID_ARGUMENTS = 10,

    JAT_STATUS_READER_INVALID_TYPE = 10001,

    JAT_STATUS_DECODER_INTERNAL_ERROR = 20000,
    JAT_STATUS_DECODER_BUFFER_OVERFLOW = 20001,
    JAT_STATUS_DECODER_INVALID_UTF8 = 20002
};

#endif
